export type Nutriments = {
  alcohol?: number
  alcohol_100g?: number
  alcohol_serving?: number
  alcohol_unit?: string
  alcohol_value?: number
  calcium?: number
  calcium100G?: number
  calciumServing?: number
  calciumUnit?: string
  calciumValue?: number
  carbohydrates?: number
  carbohydrates100G?: number
  carbohydratesServing?: number
  carbohydrates_prepared_unit?: string
  carbohydratesUnit?: string
  carbohydratesValue?: number
  cholesterol?: number
  cholesterol100G?: number
  cholesterolServing?: number
  cholesterolUnit?: string
  cholesterolValue?: number
  energy?: number
  energyKcal?: number
  energyKcal100G?: number
  energyKcalServing?: number
  energyKcalUnit?: string
  energyKcalValue?: number
  energyKcalValueComputed?: number
  energy100G?: number
  energyServing?: number
  energyUnit?: string
  energyValue?: number
  fat?: number
  fat100G?: number
  fatServing?: number
  fatUnit?: string
  fatValue?: number
  fiber?: number
  fiber100G?: number
  fiberServing?: number
  fiberUnit?: string
  fiberValue?: number
  fruitsVegetablesLegumesEstimateFromIngredients100G?: number
  fruitsVegetablesLegumesEstimateFromIngredientsServing?: number
  fruitsVegetablesNutsEstimateFromIngredients100G?: number
  fruitsVegetablesNutsEstimateFromIngredientsServing?: number
  iron?: number
  iron100G?: number
  ironServing?: number
  ironUnit?: string
  ironValue?: number
  novaGroup?: number
  novaGroup100G?: number
  novaGroupServing?: number
  nutritionScoreFr?: number
  nutritionScoreFr100G?: number
  proteins?: number
  proteins100G?: number
  proteinsServing?: number
  proteinsUnit?: string
  proteinsValue?: number
  salt?: number
  salt100G?: number
  saltServing?: number
  saltUnit?: string
  saltValue?: number
  saturatedFat?: number
  saturatedFat100G?: number
  saturatedFatServing?: number
  saturatedFatUnit?: string
  saturatedFatValue?: number
  sodium?: number
  sodium100G?: number
  sodiumServing?: number
  sodiumUnit?: string
  sodiumValue?: number
  sugars?: number
  sugars100G?: number
  sugarsServing?: number
  sugarsUnit?: string
  sugarsValue?: number
  transFat?: number
  transFat100G?: number
  transFatServing?: number
  transFatUnit?: string
  transFatValue?: number
  vitaminA?: number
  vitaminA100G?: number
  vitaminAServing?: number
  vitaminAUnit?: string
  vitaminAValue?: number
  vitaminC?: number
  vitaminC100G?: number
  vitaminCServing?: number
  vitaminCUnit?: string
  vitaminCValue?: number
}

export type NutrientLevels = {
  fat?: string
  salt?: string
  saturatedFat?: string
  sugars?: string
}
