import { Product } from "./product"
import { Veg } from "./product_ingredient"

const productMock: Product = {
  additivesN: 4,
  additivesOriginalTags: ["en:e503ii", "en:e500ii", "en:e450i", "en:e322i"],
  additivesTags: [
    "en:e322",
    "en:e322i",
    "en:e450",
    "en:e450i",
    "en:e500",
    "en:e500ii",
    "en:e503",
    "en:e503ii",
  ],
  allergens: "en:eggs,en:gluten,en:milk,en:soybeans",
  allergensFromIngredients:
    "en:milk, en:milk, en:soybeans, en:gluten, en:gluten, en:gluten, blé, blé, soja, lait, lait, blé, lactose",
  allergensFromUser: "(en) en:eggs,en:gluten,en:milk,en:soybeans",
  allergensHierarchy: ["en:eggs", "en:gluten", "en:milk", "en:soybeans"],
  allergensLc: "en",
  allergensTags: ["en:eggs", "en:gluten", "en:milk", "en:soybeans"],
  aminoAcidsPrevTags: [],
  aminoAcidsTags: [],
  brands: "Lu,Mondelez",
  brandsTags: ["lu", "mondelez"],
  categories: "Snacks, Chocolate",
  categoriesHierarchy: [
    "en:snacks",
    "en:sweet-snacks",
    "en:cocoa-and-its-products",
    "en:chocolates",
  ],
  categoriesLc: "en",
  categoriesOld: "Snacks,Snacks sucrés,Biscuits et gâteaux,Biscuits",
  categoriesProperties: {},
  categoriesPropertiesTags: [
    "all-products",
    "categories-known",
    "agribalyse-food-code-unknown",
    "agribalyse-proxy-food-code-unknown",
    "ciqual-food-code-unknown",
    "agribalyse-unknown",
  ],
  categoriesTags: [
    "en:snacks",
    "en:sweet-snacks",
    "en:cocoa-and-its-products",
    "en:chocolates",
  ],
  categoryProperties: {},
  checkersTags: ["beniben"],
  ciqualFoodNameTags: ["unknown"],
  citiesTags: [],
  code: "7622210449283",
  codesTags: [
    "code-13",
    "7622210449xxx",
    "762221044xxxx",
    "76222104xxxxx",
    "7622210xxxxxx",
    "762221xxxxxxx",
    "76222xxxxxxxx",
    "7622xxxxxxxxx",
    "762xxxxxxxxxx",
    "76xxxxxxxxxxx",
    "7xxxxxxxxxxxx",
  ],
  comparedToCategory: "en:chocolates",
  complete: 0,
  completeness: 0.9,
  countries:
    "Algeria,Belgium,France,French Polynesia,Germany,Guadeloupe,Hungary,Luxembourg,Martinique,Morocco,New Caledonia,Réunion,Spain,Switzerland,United States",
  countriesHierarchy: [
    "en:algeria",
    "en:belgium",
    "en:france",
    "en:french-polynesia",
    "en:germany",
    "en:guadeloupe",
    "en:hungary",
    "en:luxembourg",
    "en:martinique",
    "en:morocco",
    "en:new-caledonia",
    "en:reunion",
    "en:spain",
    "en:switzerland",
    "en:united-states",
  ],
  countriesLc: "en",
  countriesTags: [
    "en:algeria",
    "en:belgium",
    "en:france",
    "en:french-polynesia",
    "en:germany",
    "en:guadeloupe",
    "en:hungary",
    "en:luxembourg",
    "en:martinique",
    "en:morocco",
    "en:new-caledonia",
    "en:reunion",
    "en:spain",
    "en:switzerland",
    "en:united-states",
  ],
  createdT: 1443988064,
  creator: "openfoodfacts-contributors",
  dataQualityBugsTags: [],
  dataQualityErrorsTags: [],
  dataQualityInfoTags: [
    "en:packaging-data-incomplete",
    "en:ingredients-percent-analysis-ok",
    "en:carbon-footprint-from-known-ingredients-but-not-from-meat-or-fish",
    "en:ecoscore-extended-data-computed",
    "en:ecoscore-extended-data-less-precise-than-agribalyse",
    "en:food-groups-1-known",
    "en:food-groups-2-known",
    "en:food-groups-3-unknown",
  ],
  dataQualityTags: [
    "en:packaging-data-incomplete",
    "en:ingredients-percent-analysis-ok",
    "en:carbon-footprint-from-known-ingredients-but-not-from-meat-or-fish",
    "en:ecoscore-extended-data-computed",
    "en:ecoscore-extended-data-less-precise-than-agribalyse",
    "en:food-groups-1-known",
    "en:food-groups-2-known",
    "en:food-groups-3-unknown",
    "en:nutrition-data-per-serving-serving-quantity-is-not-recognized",
    "en:ecoscore-origins-of-ingredients-origins-are-100-percent-unknown",
    "en:ecoscore-packaging-unscored-material",
    "en:ecoscore-production-system-no-label",
  ],
  dataQualityWarningsTags: [
    "en:nutrition-data-per-serving-serving-quantity-is-not-recognized",
    "en:ecoscore-origins-of-ingredients-origins-are-100-percent-unknown",
    "en:ecoscore-packaging-unscored-material",
    "en:ecoscore-production-system-no-label",
  ],
  ecoscoreData: {
    adjustments: {
      originsOfIngredients: {
        aggregatedOrigins: [
          {
            epiScore: 0,
            origin: "en:unknown",
            percent: 100,
            transportationScore: null,
          },
        ],
        epiScore: 0,
        epiValue: -5,
        originsFromCategories: ["en:unknown"],
        originsFromOriginsField: ["en:unknown"],
        transportationScore: 0,
        transportationScores: {
          ad: 0,
          al: 0,
          at: 0,
          ax: 0,
          ba: 0,
          be: 0,
          bg: 0,
          ch: 0,
          cy: 0,
          cz: 0,
          de: 0,
          dk: 0,
          dz: 0,
          ee: 0,
          eg: 0,
          es: 0,
          fi: 0,
          fo: 0,
          fr: 0,
          gg: 0,
          gi: 0,
          gr: 0,
          hr: 0,
          hu: 0,
          ie: 0,
          il: 0,
          im: 0,
          is: 0,
          it: 0,
          je: 0,
          lb: 0,
          li: 0,
          lt: 0,
          lu: 0,
          lv: 0,
          ly: 0,
          ma: 0,
          mc: 0,
          md: 0,
          me: 0,
          mk: 0,
          mt: 0,
          nl: 0,
          no: 0,
          pl: 0,
          ps: 0,
          pt: 0,
          ro: 0,
          rs: 0,
          se: 0,
          si: 0,
          sj: 0,
          sk: 0,
          sm: 0,
          sy: 0,
          tn: 0,
          tr: 0,
          ua: 0,
          uk: 0,
          us: 0,
          va: 0,
          world: 0,
          xk: 0,
        },
        transportationValue: 0,
        transportationValues: {
          ad: 0,
          al: 0,
          at: 0,
          ax: 0,
          ba: 0,
          be: 0,
          bg: 0,
          ch: 0,
          cy: 0,
          cz: 0,
          de: 0,
          dk: 0,
          dz: 0,
          ee: 0,
          eg: 0,
          es: 0,
          fi: 0,
          fo: 0,
          fr: 0,
          gg: 0,
          gi: 0,
          gr: 0,
          hr: 0,
          hu: 0,
          ie: 0,
          il: 0,
          im: 0,
          is: 0,
          it: 0,
          je: 0,
          lb: 0,
          li: 0,
          lt: 0,
          lu: 0,
          lv: 0,
          ly: 0,
          ma: 0,
          mc: 0,
          md: 0,
          me: 0,
          mk: 0,
          mt: 0,
          nl: 0,
          no: 0,
          pl: 0,
          ps: 0,
          pt: 0,
          ro: 0,
          rs: 0,
          se: 0,
          si: 0,
          sj: 0,
          sk: 0,
          sm: 0,
          sy: 0,
          tn: 0,
          tr: 0,
          ua: 0,
          uk: 0,
          us: 0,
          va: 0,
          world: 0,
          xk: 0,
        },
        value: -5,
        values: {
          ad: -5,
          al: -5,
          at: -5,
          ax: -5,
          ba: -5,
          be: -5,
          bg: -5,
          ch: -5,
          cy: -5,
          cz: -5,
          de: -5,
          dk: -5,
          dz: -5,
          ee: -5,
          eg: -5,
          es: -5,
          fi: -5,
          fo: -5,
          fr: -5,
          gg: -5,
          gi: -5,
          gr: -5,
          hr: -5,
          hu: -5,
          ie: -5,
          il: -5,
          im: -5,
          is: -5,
          it: -5,
          je: -5,
          lb: -5,
          li: -5,
          lt: -5,
          lu: -5,
          lv: -5,
          ly: -5,
          ma: -5,
          mc: -5,
          md: -5,
          me: -5,
          mk: -5,
          mt: -5,
          nl: -5,
          no: -5,
          pl: -5,
          ps: -5,
          pt: -5,
          ro: -5,
          rs: -5,
          se: -5,
          si: -5,
          sj: -5,
          sk: -5,
          sm: -5,
          sy: -5,
          tn: -5,
          tr: -5,
          ua: -5,
          uk: -5,
          us: -5,
          va: -5,
          world: -5,
          xk: -5,
        },
        warning: "origins_are_100_percent_unknown",
      },
      packaging: {
        nonRecyclableAndNonBiodegradableMaterials: 0,
        packagings: [
          {
            ecoscoreMaterialScore: 0,
            ecoscoreShapeRatio: 0.1,
            material: "en:plastic",
            number_of_units: 1,
            quantity_per_unit: "300 g",
            quantity_per_unit_unit: "g",
            quantity_per_unit_value: 300,
            recycling: "en:recycle",
            shape: "en:film",
            weight_measured: 3.35,
          },
          {
            ecoscoreMaterialScore: 0,
            ecoscoreShapeRatio: 1,
            material: "fr:Papier ondulé",
            number_of_units: 1,
            quantity_per_unit: "300 g",
            quantity_per_unit_unit: "g",
            quantity_per_unit_value: 300,
            recycling: "en:recycle",
            shape: "en:sleeve",
            weight_measured: 3.54,
          },
        ],
        score: -10,
        value: -11,
        warning: "unscored_material",
      },
      productionSystem: {
        labels: [],
        value: 0,
        warning: "no_label",
      },
      threatenedSpecies: {
        ingredient: "en:palm-oil",
        value: -10,
      },
    },
    agribalyse: {
      warning: "missing_agribalyse_match",
    },
    missing: {
      agbCategory: 1,
      labels: 1,
      origins: 1,
      packagings: 1,
    },
    missingAgribalyseMatchWarning: 1,
    scores: {},
    status: "unknown",
  },
  ecoscoreGrade: "unknown",
  ecoscoreTags: ["unknown"],
  entryDatesTags: ["2015-10-04", "2015-10", "2015"],
  expirationDate: "31/07/2020",
  foodGroups: "en:chocolate-products",
  foodGroupsTags: ["en:sugary-snacks", "en:chocolate-products"],
  fruitsVegetablesNuts100GEstimate: 0,
  genericName: "BISCUITS FOURRÉS (35%) PARFUM CHOCOLAT",
  genericNameEn: "",
  genericNameEs: "",
  genericNameFr: "BISCUITS FOURRÉS (35%) PARFUM CHOCOLAT",
  id: "7622210449283",
  imageFrontSmallURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.200.jpg",
  imageFrontThumbURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.100.jpg",
  imageFrontURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.400.jpg",
  imageIngredientsSmallURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.200.jpg",
  imageIngredientsThumbURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.100.jpg",
  imageIngredientsURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.400.jpg",
  imageNutritionSmallURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.200.jpg",
  imageNutritionThumbURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.100.jpg",
  imageNutritionURL:
    "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.400.jpg",
  ingredients: [
    {
      id: "en:cereal",
      ingredients: [
        {
          ciqualProxyFoodCode: "9410",
          id: "en:wheat-flour",
          percent: 35,
          percentEstimate: 35,
          percentMax: 35,
          percentMin: 35,
          text: "Farine de _blé_",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
        {
          ciqualProxyFoodCode: "9410",
          id: "en:whole-wheat-flour",
          percent: 15.7,
          percentEstimate: 15.7,
          percentMax: 15.7,
          percentMin: 15.7,
          text: "farine de _blé_complète",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
      ],
      percentEstimate: 50.7,
      percentMax: 50.7,
      percentMin: 50.7,
      text: "Céréale",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "31016",
      id: "en:sugar",
      percentEstimate: 20.15,
      percentMax: 35.8,
      percentMin: 4.5,
      text: "sucre",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "16129",
      id: "en:palm-oil",
      percentEstimate: 16.825,
      percentMax: 30.3333333333333,
      percentMin: 4.5,
      text: "huiles végétales de palme",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "17130",
      id: "en:colza-oil",
      percentEstimate: 8.4125,
      percentMax: 22.4,
      percentMin: 4.5,
      text: "huiles végétales de colza",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "18100",
      id: "en:fat-reduced-cocoa-powder",
      percentEstimate: 3.91249999999999,
      percentMax: 4.5,
      percentMin: 4.5,
      text: "cacao maigre en poudre",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "31016",
      id: "en:glucose-syrup",
      percentEstimate: 0,
      percentMax: 4.5,
      percentMin: 0,
      text: "sirop de glucose",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "9510",
      id: "en:wheat-starch",
      percentEstimate: 0,
      percentMax: 4.5,
      percentMin: 0,
      text: "amidon de _blé_",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      id: "en:raising-agent",
      ingredients: [
        {
          id: "en:e503ii",
          percent: 4.5,
          percentEstimate: 0,
          percentMax: 4.5,
          percentMin: 0,
          text: "carbonates acide d'ammonium",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
        {
          id: "en:e500ii",
          percent: 2.25,
          percentEstimate: 0,
          percentMax: 2.25,
          percentMin: 0,
          text: "carbonates acide de sodium",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
        {
          id: "en:e450i",
          percent: 1.5,
          percentEstimate: 0,
          percentMax: 1.5,
          percentMin: 0,
          text: "diphosphate disodique",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
      ],
      percentEstimate: 0,
      percentMax: 4.5,
      percentMin: 0,
      text: "poudres à lever",
    },
    {
      id: "en:emulsifier",
      ingredients: [
        {
          ciqualFoodCode: "42200",
          id: "en:soya-lecithin",
          percent: 4.5,
          percentEstimate: 0,
          percentMax: 4.5,
          percentMin: 0,
          text: "lécithines de _soja_",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
        {
          id: "en:sunflower-lecithin",
          percent: 2.25,
          percentEstimate: 0,
          percentMax: 2.25,
          percentMin: 0,
          text: "lécithine de tournesol",
          vegan: Veg.Yes,
          vegetarian: Veg.Yes,
        },
      ],
      percentEstimate: 0,
      percentMax: 4.5,
      percentMin: 0,
      text: "émulsifiant",
    },
    {
      ciqualFoodCode: "11058",
      id: "en:salt",
      percentEstimate: 0,
      percentMax: 0.49,
      percentMin: 0,
      text: "sel",
      vegan: Veg.Yes,
      vegetarian: Veg.Yes,
    },
    {
      ciqualFoodCode: "19054",
      id: "en:skimmed-milk-powder",
      percentEstimate: 0,
      percentMax: 0.49,
      percentMin: 0,
      text: "_lait_ écrémé en poudre",
      vegan: Veg.No,
      vegetarian: Veg.Yes,
    },
    {
      id: "en:lactose-and-milk-proteins",
      percentEstimate: 0,
      percentMax: 0.49,
      percentMin: 0,
      text: "lactose et protéines de _lait_",
      vegan: Veg.No,
      vegetarian: Veg.Yes,
    },
    {
      id: "en:flavouring",
      percentEstimate: 0,
      percentMax: 0.49,
      percentMin: 0,
      text: "arômes",
      vegan: Veg.Maybe,
      vegetarian: Veg.Maybe,
    },
  ],
  ingredientsAnalysis: {
    "en:maybe-vegetarian": ["en:flavouring"],
    "en:non-vegan": ["en:skimmed-milk-powder", "en:lactose-and-milk-proteins"],
    "en:palm-oil": ["en:palm-oil"],
  },
  ingredientsAnalysisTags: [
    "en:palm-oil",
    "en:non-vegan",
    "en:maybe-vegetarian",
  ],
  ingredientsDebug: [
    "Céréale 50",
    ",",
    null,
    null,
    null,
    "7 % ",
    "(",
    "(",
    null,
    null,
    "farine de blé 35 %",
    ",",
    null,
    null,
    null,
    " farine de blé complète 15",
    ",",
    null,
    null,
    null,
    "7 %)",
    ",",
    null,
    null,
    null,
    " sucre",
    ",",
    null,
    null,
    null,
    " huiles végétales ",
    "(",
    "(",
    null,
    null,
    "palme",
    ",",
    null,
    null,
    null,
    " colza)",
    ",",
    null,
    null,
    null,
    " cacao maigre en poudre 4",
    ",",
    null,
    null,
    null,
    "5 %",
    ",",
    null,
    null,
    null,
    " sirop de glucose",
    ",",
    null,
    null,
    null,
    " amidon de blé",
    ",",
    null,
    null,
    null,
    " poudre à lever ",
    ":",
    ":",
    null,
    null,
    " ",
    "(",
    "(",
    null,
    null,
    "carbonate acide d'ammonium",
    ",",
    null,
    null,
    null,
    " carbonate acide de sodium",
    ",",
    null,
    null,
    null,
    " diphosphate disodique)",
    ",",
    null,
    null,
    null,
    " émulsifiants ",
    ":",
    ":",
    null,
    null,
    " ",
    "(",
    "(",
    null,
    null,
    "lécithine de soja",
    ",",
    null,
    null,
    null,
    " lécithine de tournesol)",
    ",",
    null,
    null,
    null,
    " sel",
    ",",
    null,
    null,
    null,
    " lait écrémé en poudre",
    ",",
    null,
    null,
    null,
    " lactose et protéines de lait",
    ",",
    null,
    null,
    null,
    " arômes.",
  ],
  ingredientsFromOrThatMayBeFromPalmOilN: 1,
  ingredientsFromPalmOilN: 1,
  ingredientsOriginalTags: ["huile-de-palme"],
  ingredientsHierarchy: [
    "en:cereal",
    "en:sugar",
    "en:added-sugar",
    "en:disaccharide",
    "en:palm-oil",
    "en:oil-and-fat",
    "en:vegetable-oil-and-fat",
    "en:palm-oil-and-fat",
    "en:colza-oil",
    "en:rapeseed-oil",
    "en:fat-reduced-cocoa-powder",
    "en:plant",
    "en:cocoa",
    "en:cocoa-powder",
    "en:glucose-syrup",
    "en:monosaccharide",
    "en:glucose",
    "en:wheat-starch",
    "en:starch",
    "en:raising-agent",
    "en:emulsifier",
    "en:salt",
    "en:skimmed-milk-powder",
    "en:dairy",
    "en:milk-powder",
    "en:lactose-and-milk-proteins",
    "en:protein",
    "en:animal-protein",
    "en:milk-proteins",
    "en:lactose",
    "en:flavouring",
    "en:wheat-flour",
    "en:flour",
    "en:wheat",
    "en:cereal-flour",
    "en:whole-wheat-flour",
    "en:wholemeal-flour",
    "en:e503ii",
    "en:e503",
    "en:e500ii",
    "en:e500",
    "en:e450i",
    "en:e450",
    "en:soya-lecithin",
    "en:e322",
    "en:e322i",
    "en:sunflower-lecithin",
  ],
  ingredientsIDSDebug: [
    "cereale-50",
    "7",
    "farine-de-ble-35",
    "farine-de-ble-complete-15",
    "7",
    "sucre",
    "huiles-vegetales",
    "palme",
    "colza",
    "cacao-maigre-en-poudre-4",
    "5",
    "sirop-de-glucose",
    "amidon-de-ble",
    "poudre-a-lever",
    "carbonate-acide-d-ammonium",
    "carbonate-acide-de-sodium",
    "diphosphate-disodique",
    "emulsifiants",
    "lecithine-de-soja",
    "lecithine-de-tournesol",
    "sel",
    "lait-ecreme-en-poudre",
    "lactose-et-proteines-de-lait",
    "aromes",
  ],
  ingredientsLc: "fr",
  ingredientsN: 20,
  ingredientsNTags: ["20", "11-20"],
  ingredientsPercentAnalysis: 1,
  ingredientsTags: [
    "en:cereal",
    "en:sugar",
    "en:added-sugar",
    "en:disaccharide",
    "en:palm-oil",
    "en:oil-and-fat",
    "en:vegetable-oil-and-fat",
    "en:palm-oil-and-fat",
    "en:colza-oil",
    "en:rapeseed-oil",
    "en:fat-reduced-cocoa-powder",
    "en:plant",
    "en:cocoa",
    "en:cocoa-powder",
    "en:glucose-syrup",
    "en:monosaccharide",
    "en:glucose",
    "en:wheat-starch",
    "en:starch",
    "en:raising-agent",
    "en:emulsifier",
    "en:salt",
    "en:skimmed-milk-powder",
    "en:dairy",
    "en:milk-powder",
    "en:lactose-and-milk-proteins",
    "en:protein",
    "en:animal-protein",
    "en:milk-proteins",
    "en:lactose",
    "en:flavouring",
    "en:wheat-flour",
    "en:flour",
    "en:wheat",
    "en:cereal-flour",
    "en:whole-wheat-flour",
    "en:wholemeal-flour",
    "en:e503ii",
    "en:e503",
    "en:e500ii",
    "en:e500",
    "en:e450i",
    "en:e450",
    "en:soya-lecithin",
    "en:e322",
    "en:e322i",
    "en:sunflower-lecithin",
  ],
  ingredientsText:
    "Céréale 50,7% (Farine de _blé_ 35%, farine de _blé_complète 15,7%), sucre, huiles végétales (palme, colza), cacao maigre en poudre 4,5%, sirop de glucose, amidon de _blé_, poudres à lever (carbonates acide d'ammonium, carbonates acide de sodium, diphosphate disodique), émulsifiant (lécithines de _soja_, lécithine de tournesol), sel, _lait_ écrémé en poudre, lactose et protéines de _lait_, arômes.\r\n\r\nPeut contenir _œuf_.",
  ingredientsTextEn:
    "Cereal 50.7% (_wheat_ flour 35%, _whole_wheat_ flour 15.7%), sugar, vegetable oils (palm, rapeseed), low-fat cocoa powder 4.5%, glucose syrup, _wheat_ starch, raising agents (ammonium bicarbonate, baking soda, disodium diphosphate), emulsifier (soy lecithin, sunflower lecithin), salt, skimmed _milk_ powder, lactose and _milk_ protein, flavourings. May contain _egg_.",
  ingredientsTextEs: "",
  ingredientsTextFr:
    "Céréale 50,7% (Farine de _blé_ 35%, farine de _blé_complète 15,7%), sucre, huiles végétales (palme, colza), cacao maigre en poudre 4,5%, sirop de glucose, amidon de _blé_, poudres à lever (carbonates acide d'ammonium, carbonates acide de sodium, diphosphate disodique), émulsifiant (lécithines de _soja_, lécithine de tournesol), sel, _lait_ écrémé en poudre, lactose et protéines de _lait_, arômes.\r\n\r\nPeut contenir _œuf_.",
  ingredientsTextWithAllergens:
    'Céréale 50,7% (Farine de <span class="allergen">blé</span> 35%, farine de _<span class="allergen">blé</span>_complète 15,7%), sucre, huiles végétales (palme, colza), cacao maigre en poudre 4,5%, sirop de glucose, amidon de <span class="allergen">blé</span>, poudres à lever (carbonates acide d\'ammonium, carbonates acide de sodium, diphosphate disodique), émulsifiant (lécithines de <span class="allergen">soja</span>, lécithine de tournesol), sel, <span class="allergen">lait</span> écrémé en poudre, <span class="allergen">lactose</span> et protéines de <span class="allergen">lait</span>, arômes.\r\n\r\nPeut contenir <span class="allergen">œuf</span>.',
  ingredientsTextWithAllergensEn:
    'Cereal 50.7% (<span class="allergen">wheat</span> flour 35%, _whole_<span class="allergen">wheat</span>_ flour 15.7%), sugar, vegetable oils (palm, rapeseed), low-fat cocoa powder 4.5%, glucose syrup, <span class="allergen">wheat</span> starch, raising agents (ammonium bicarbonate, baking soda, disodium diphosphate), emulsifier (<span class="allergen">soy lecithin</span>, sunflower lecithin), salt, skimmed <span class="allergen">milk</span> powder, <span class="allergen">lactose</span> and <span class="allergen">milk</span> protein, flavourings. May contain <span class="allergen">egg</span>.',
  ingredientsTextWithAllergensEs: "",
  ingredientsTextWithAllergensFr:
    'Céréale 50,7% (Farine de <span class="allergen">blé</span> 35%, farine de _<span class="allergen">blé</span>_complète 15,7%), sucre, huiles végétales (palme, colza), cacao maigre en poudre 4,5%, sirop de glucose, amidon de <span class="allergen">blé</span>, poudres à lever (carbonates acide d\'ammonium, carbonates acide de sodium, diphosphate disodique), émulsifiant (lécithines de <span class="allergen">soja</span>, lécithine de tournesol), sel, <span class="allergen">lait</span> écrémé en poudre, <span class="allergen">lactose</span> et protéines de <span class="allergen">lait</span>, arômes.\r\n\r\nPeut contenir <span class="allergen">œuf</span>.',
  ingredientsThatMayBeFromPalmOilN: 0,
  ingredientsThatMayBeFromPalmOilTags: [],
  ingredientsWithSpecifiedPercentN: 3,
  ingredientsWithSpecifiedPercentSum: 55.2,
  ingredientsWithUnspecifiedPercentN: 14,
  ingredientsWithUnspecifiedPercentSum: 45.3875,
  ingredientsWithoutCiqualCodes: [
    "en:cereal",
    "en:e450i",
    "en:e500ii",
    "en:e503ii",
    "en:emulsifier",
    "en:flavouring",
    "en:lactose-and-milk-proteins",
    "en:raising-agent",
    "en:sunflower-lecithin",
  ],
  ingredientsWithoutCiqualCodesN: 9,
  knownIngredientsN: 47,
  labels: "Sin gluten",
  labelsLc: "en",
  labelsOld: "Labels de distributeurs,en:Charte LU Harmony,Point Vert,Triman",
  labelsTags: ["en:sin-gluten"],
  lang: "fr",
  languagesCodes: {
    en: 3,
    es: 2,
    fr: 7,
  },
  languagesHierarchy: [
    "en:arabic",
    "en:english",
    "en:french",
    "en:spanish",
    "en:ukrainian",
  ],
  languagesTags: [
    "en:arabic",
    "en:english",
    "en:french",
    "en:spanish",
    "en:ukrainian",
    "en:5",
    "en:multilingual",
  ],
  lastImageT: 1721115343,
  lastModifiedT: 1727884138,
  lastUpdatedT: 1727884138,
  lc: "fr",
  link: "https://www.lu.fr/prince",
  maxImgid: "231",
  miscTags: [
    "en:ecoscore-changed",
    "en:ecoscore-extended-data-computed",
    "en:ecoscore-extended-data-version-4",
    "en:ecoscore-grade-changed",
    "en:ecoscore-not-computed",
    "en:nutriscore-2021-better-than-2023",
    "en:nutriscore-2021-d-2023-e",
    "en:nutriscore-2021-different-from-2023",
    "en:nutriscore-computed",
    "en:nutrition-all-nutriscore-values-known",
    "en:nutrition-fruits-vegetables-legumes-estimate-from-ingredients",
    "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
    "en:packagings-complete",
    "en:packagings-not-empty",
    "en:packagings-number-of-components-2",
    "en:packagings-with-all-weights",
    "en:packagings-with-all-weights-complete",
    "en:packagings-with-weights",
    "en:some-ingredients-with-specified-percent",
    "en:main-countries-be-unexpectedly-low-scans",
    "en:main-countries-be-unexpectedly-low-scans-10-20-percent-of-expected",
    "en:main-countries-pf-unexpectedly-low-scans",
    "en:main-countries-pf-unexpectedly-low-scans-0-10-percent-of-expected",
    "en:main-countries-de-unexpectedly-low-scans",
    "en:main-countries-de-unexpectedly-low-scans-0-10-percent-of-expected",
    "en:main-countries-de-unexpectedly-low-scans-and-no-data-in-country-language",
    "en:main-countries-de-product-name-not-in-country-language",
    "en:main-countries-de-ingredients-not-in-country-language",
    "en:main-countries-de-no-data-in-country-language",
    "en:main-countries-hu-unexpectedly-low-scans",
    "en:main-countries-hu-unexpectedly-low-scans-0-10-percent-of-expected",
    "en:main-countries-hu-unexpectedly-low-scans-and-no-data-in-country-language",
    "en:main-countries-hu-product-name-not-in-country-language",
    "en:main-countries-hu-ingredients-not-in-country-language",
    "en:main-countries-hu-no-data-in-country-language",
    "en:main-countries-ma-unexpectedly-low-scans",
    "en:main-countries-ma-unexpectedly-low-scans-20-30-percent-of-expected",
    "en:main-countries-es-unexpectedly-low-scans",
    "en:main-countries-es-unexpectedly-low-scans-0-10-percent-of-expected",
    "en:main-countries-es-unexpectedly-low-scans-and-only-1-field-in-country-language",
    "en:main-countries-es-ingredients-not-in-country-language",
    "en:main-countries-es-only-1-field-in-country-language",
    "en:main-countries-ch-unexpectedly-low-scans",
    "en:main-countries-ch-unexpectedly-low-scans-20-30-percent-of-expected",
    "en:main-countries-us-unexpectedly-low-scans",
    "en:main-countries-us-unexpectedly-low-scans-0-10-percent-of-expected",
  ],
  noNutritionData: "",
  novaGroup: 4,
  novaGroups: "4",
  novaGroupsMarkers: {
    "3": [
      ["categories", "en:chocolates"],
      ["ingredients", "en:salt"],
      ["ingredients", "en:starch"],
      ["ingredients", "en:sugar"],
      ["categories", "en:sweet-snacks"],
      ["ingredients", "en:milk-powder"],
    ],
    "4": [
      ["additives", "en:e322"],
      ["additives", "en:e450"],
      ["ingredients", "en:emulsifier"],
      ["ingredients", "en:flavouring"],
      ["ingredients", "en:glucose"],
      ["ingredients", "en:glucose-syrup"],
      ["ingredients", "en:lactose"],
      ["ingredients", "en:milk-proteins"],
    ],
  },
  novaGroupsTags: ["en:4-ultra-processed-food-and-drink-products"],
  nucleotidesPrevTags: [],
  nucleotidesTags: [],
  nutrientLevels: {
    fat: "moderate",
    salt: "moderate",
    saturatedFat: "high",
    sugars: "high",
  },
  nutrientLevelsTags: [
    "en:fat-in-moderate-quantity",
    "en:saturated-fat-in-high-quantity",
    "en:sugars-in-high-quantity",
    "en:salt-in-moderate-quantity",
  ],
  nutriments: {
    alcohol: 0,
    alcohol_100g: 0,
    alcohol_serving: 0,
    alcohol_unit: "% vol",
    alcohol_value: 0,
    carbohydrates: 69,
    carbohydrates100G: 69,
    carbohydrates_prepared_unit: "g",
    carbohydratesUnit: "g",
    carbohydratesValue: 69,
    energy: 1962,
    energy100G: 1962,
    energyUnit: "kJ",
    energyValue: 1962,
    fat: 17,
    fat100G: 17,
    fatUnit: "g",
    fatValue: 17,
    fiber: 4,
    fiber100G: 4,
    fiberUnit: "g",
    fiberValue: 4,
    proteins: 6.3,
    proteins100G: 6.3,
    proteinsUnit: "g",
    proteinsValue: 6.3,
    salt: 0.49,
    salt100G: 0.49,
    saltUnit: "g",
    saltValue: 0.49,
    sodium: 0.196,
    sodium100G: 0.196,
    sodiumUnit: "g",
    sodiumValue: 0.196,
    sugars: 32,
    sugars100G: 32,
    sugarsUnit: "g",
    sugarsValue: 32,
  },
  nutriscore: {
    "2021": {
      categoryAvailable: 1,
      data: {
        energy: 1962,
        energyPoints: 5,
        energyValue: 1962,
        fiber: 4,
        fiberPoints: 4,
        fiberValue: 4,
        fruitsVegetablesNutsColzaWalnutOliveOils: 8.4125,
        fruitsVegetablesNutsColzaWalnutOliveOilsPoints: 0,
        fruitsVegetablesNutsColzaWalnutOliveOilsValue: 8.4,
        isBeverage: 0,
        isCheese: 0,
        isFat: 0,
        isWater: 0,
        negativePoints: 19,
        positivePoints: 4,
        proteins: 6.3,
        proteinsPoints: 3,
        proteinsValue: 6.3,
        saturatedFat: 5.6,
        saturatedFatPoints: 5,
        saturatedFatValue: 5.6,
        sodium: 196,
        sodiumPoints: 2,
        sodiumValue: 196,
        sugars: 32,
        sugarsPoints: 7,
        sugarsValue: 32,
      },
      grade: "d",
      nutrientsAvailable: 1,
      nutriscoreApplicable: 1,
      nutriscoreComputed: 1,
      score: 15,
    },
    "2023": {
      categoryAvailable: 1,
      data: {
        components: {
          negative: [
            {
              id: "energy",
              points: 5,
              pointsMax: 10,
              unit: "kJ",
              value: 1962,
            },
            {
              id: "sugars",
              points: 9,
              pointsMax: 15,
              unit: "g",
              value: 32,
            },
            {
              id: "saturated_fat",
              points: 5,
              pointsMax: 10,
              unit: "g",
              value: 5.6,
            },
            {
              id: "salt",
              points: 2,
              pointsMax: 20,
              unit: "g",
              value: 0.49,
            },
          ],
          positive: [
            {
              id: "fiber",
              points: 1,
              pointsMax: 5,
              unit: "g",
              value: 4,
            },
            {
              id: "fruits_vegetables_legumes",
              points: 0,
              pointsMax: 5,
              unit: "%",
              value: 0,
            },
          ],
        },
        countProteins: 0,
        countProteinsReason: "negative_points_greater_than_or_equal_to_11",
        isBeverage: 0,
        isCheese: 0,
        isFatOilNutsSeeds: 0,
        isRedMeatProduct: 0,
        isWater: 0,
        negativePoints: 21,
        negativePointsMax: 55,
        positiveNutrients: ["fiber", "fruits_vegetables_legumes"],
        positivePoints: 1,
        positivePointsMax: 10,
      },
      grade: "e",
      nutrientsAvailable: 1,
      nutriscoreApplicable: 1,
      nutriscoreComputed: 1,
      score: 20,
    },
  },
  nutriscore2021_Tags: ["d"],
  nutriscore2023_Tags: ["e"],
  nutriscoreData: {
    energy: 1962,
    energyPoints: 5,
    energyValue: 1962,
    fiber: 4,
    fiberPoints: 4,
    fiberValue: 4,
    fruitsVegetablesNutsColzaWalnutOliveOils: 8.4125,
    fruitsVegetablesNutsColzaWalnutOliveOilsPoints: 0,
    fruitsVegetablesNutsColzaWalnutOliveOilsValue: 8.4,
    grade: "d",
    isBeverage: 0,
    isCheese: 0,
    isFat: 0,
    isWater: 0,
    negativePoints: 19,
    positivePoints: 4,
    proteins: 6.3,
    proteinsPoints: 3,
    proteinsValue: 6.3,
    saturatedFat: 5.6,
    saturatedFatPoints: 5,
    saturatedFatValue: 5.6,
    score: 15,
    sodium: 196,
    sodiumPoints: 2,
    sodiumValue: 196,
    sugars: 32,
    sugarsPoints: 7,
    sugarsValue: 32,
  },
  nutriscoreGrade: "d",
  nutriscoreScore: 15,
  nutriscoreScoreOpposite: -15,
  nutriscoreTags: ["d"],
  nutriscoreVersion: "2021",
  nutritionData: "on",
  nutritionDataPer: "100g",
  nutritionDataPrepared: "",
  nutritionDataPreparedPer: "100g",
  nutritionScoreBeverage: 0,
  nutritionScoreWarningFruitsVegetablesLegumesEstimateFromIngredients: 1,
  nutritionScoreWarningFruitsVegetablesLegumesEstimateFromIngredientsValue: 0,
  nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredients: 1,
  nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredientsValue: 8.4125,
  packaging: "Packet,Hdpe film-packet,Etui en carton,Film en plastique",
  packagingHierarchy: [
    "en:packet",
    "en:Etui en carton",
    "en:Film en plastique",
    "en:Hdpe film-packet",
  ],
  packagingLc: "en",
  packagingMaterialsTags: ["en:plastic", "fr:Papier ondulé"],
  packagingOld: "Paquet, Etui en carton, Film en plastique",
  packagingOldBeforeTaxonomization:
    "fr:Film en plastique,paquet,fr:Etui en carton",
  packagingRecyclingTags: ["en:recycle"],
  packagingShapesTags: ["en:film", "en:sleeve"],
  packagingTags: [
    "en:packet",
    "en:etui-en-carton",
    "en:film-en-plastique",
    "en:hdpe-film-packet",
  ],
  packagingText:
    "1 film en plastique à recycler\r\n1 étui en papier ondulé à recycler",
  packagingTextFr:
    "1 film en plastique à recycler\r\n1 étui en papier ondulé à recycler",
  packagings: [
    {
      number_of_units: 1,
      quantity_per_unit: "300 g",
      quantity_per_unit_unit: "g",
      quantity_per_unit_value: 300,
      recycling: {
        id: "en:recycle",
      },
      shape: {
        id: "en:film",
      },
      weight_measured: 3.35,
    },
    {
      number_of_units: 1,
      quantity_per_unit: "300 g",
      quantity_per_unit_unit: "g",
      quantity_per_unit_value: 300,
      recycling: {
        id: "en:recycle",
      },
      shape: {
        id: "en:sleeve",
      },
      weight_measured: 3.54,
    },
  ],
  packagingsComplete: 1,
  packagingsMaterials: {
    all: {
      weight: 6.89,
      weight_100g: 6.89,
      weight_percent: 100,
    },
    endPlastic: {
      weight: 3.35,
      weight_100g: 3.35,
      weight_percent: 48.6211901306241,
    },
    enUnknown: {
      weight: 3.54,
      weight_100g: 3.54,
      weight_percent: 51.3788098693759,
    },
  },
  packagingsN: 2,
  pnnsGroups1: "Sugary snacks",
  pnnsGroups1_Tags: ["sugary-snacks", "known"],
  pnnsGroups2: "Chocolate products",
  pnnsGroups2_Tags: ["chocolate-products", "known"],
  popularityKey: 22999991602,
  productName: "Prince Chocolat biscuits au blé complet",
  productNameEs: "Chocolate con leche",
  productNameEn: "Prince chocolate",
  productNameFr: "Prince Chocolat biscuits au blé complet",
  productQuantity: "100",
  productQuantityUnit: "g",
  productType: "food",
  purchasePlaces: "F-77480 Mousseaux-les-Bray,France",
  purchasePlacesTags: ["f-77480-mousseaux-les-bray", "france"],
  quantity: "100g",
  removedCountriesTags: [],
  rev: 623,
  scansN: 1849,
  selectedImages: {
    front: {
      display: {
        en: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.400.jpg",
        es: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_es.590.400.jpg",
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_fr.584.400.jpg",
      },
      small: {
        en: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.200.jpg",
        es: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_es.590.200.jpg",
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_fr.584.200.jpg",
      },
      thumb: {
        en: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.100.jpg",
        es: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_es.590.100.jpg",
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_fr.584.100.jpg",
      },
    },
    ingredients: {
      display: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.400.jpg",
      },
      small: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.200.jpg",
      },
      thumb: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/ingredients_fr.593.100.jpg",
      },
    },
    nutrition: {
      display: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.400.jpg",
      },
      small: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.200.jpg",
      },
      thumb: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/nutrition_fr.568.100.jpg",
      },
    },
    packaging: {
      display: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/packaging_fr.622.400.jpg",
      },
      small: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/packaging_fr.622.200.jpg",
      },
      thumb: {
        fr: "https://images.openfoodfacts.org/images/products/762/221/044/9283/packaging_fr.622.100.jpg",
      },
    },
  },
  servingQuantityUnit: "g",
  servingSize: "20",
  sortkey: 1610831524,
  states:
    "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:packaging-photo-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded",
  statesHierarchy: [
    "en:to-be-completed",
    "en:nutrition-facts-completed",
    "en:ingredients-completed",
    "en:expiration-date-completed",
    "en:packaging-code-to-be-completed",
    "en:characteristics-to-be-completed",
    "en:origins-to-be-completed",
    "en:categories-completed",
    "en:brands-completed",
    "en:packaging-completed",
    "en:quantity-completed",
    "en:product-name-completed",
    "en:photos-validated",
    "en:packaging-photo-selected",
    "en:nutrition-photo-selected",
    "en:ingredients-photo-selected",
    "en:front-photo-selected",
    "en:photos-uploaded",
  ],
  statesTags: [
    "en:to-be-completed",
    "en:nutrition-facts-completed",
    "en:ingredients-completed",
    "en:expiration-date-completed",
    "en:packaging-code-to-be-completed",
    "en:characteristics-to-be-completed",
    "en:origins-to-be-completed",
    "en:categories-completed",
    "en:brands-completed",
    "en:packaging-completed",
    "en:quantity-completed",
    "en:product-name-completed",
    "en:photos-validated",
    "en:packaging-photo-selected",
    "en:nutrition-photo-selected",
    "en:ingredients-photo-selected",
    "en:front-photo-selected",
    "en:photos-uploaded",
  ],
  stores:
    "Carrefour Market,Magasins U,Auchan,Intermarché,Carrefour,Casino,Cora,Bi1,carrefour.fr,Netto,bannete,E.Leclerc",
  storesTags: [
    "carrefour-market",
    "magasins-u",
    "auchan",
    "intermarche",
    "carrefour",
    "casino",
    "cora",
    "bi1",
    "carrefour-fr",
    "netto",
    "bannete",
    "e-leclerc",
  ],
  teams:
    "pain-au-chocolat,shark-attack,chocolatine,la-robe-est-bleue,stakano,dietreflux,m,b,c,swipe-studio,gmlaa,heathy-app-cross-eat",
  teamsTags: [
    "pain-au-chocolat",
    "shark-attack",
    "chocolatine",
    "la-robe-est-bleue",
    "stakano",
    "dietreflux",
    "m",
    "b",
    "c",
    "swipe-studio",
    "gmlaa",
    "heathy-app-cross-eat",
  ],
  traces: "en:eggs",
  tracesFromIngredients: "œuf",
  tracesFromUser: "(en) en:eggs",
  tracesHierarchy: ["en:eggs"],
  tracesLc: "en",
  tracesTags: ["en:eggs"],
  uniqueScansN: 1592,
  unknownIngredientsN: 0,
  unknownNutrientsTags: [],
  updateKey: "add-product-type",
  vitaminsPrevTags: [],
  vitaminsTags: [],
  weighersTags: ["xavier-m", "fgouget"],
}
export default productMock
