import {
  CategoriesProperties,
  EcoscoreData,
  Languages,
  LanguagesCodes,
  PackagingsMaterials,
  ProductPackaging,
  SelectedImages,
  Source,
  SourcesFields,
} from "./food_data"

import { Images } from "./image"
import { NutrientLevels, Nutriments } from "./nutriments"
import { Nutriscore, NutriscoreData } from "./nutriscore"
import { ProductIngredient } from "./product_ingredient"

export type Product = {
  id?: string
  keywords?: string[]
  addedCountriesTags?: any[]
  additivesDebugTags?: any[]
  additivesN?: number
  additivesOldN?: number
  additivesOldTags?: string[]
  additivesOriginalTags?: string[]
  additivesPrevOriginalTags?: string[]
  additivesTags?: string[]
  allergens?: string
  allergensFromIngredients?: string
  allergensFromUser?: string
  allergensHierarchy?: string[]
  allergensLc?: string
  allergensTags?: string[]
  aminoAcidsPrevTags?: any[]
  aminoAcidsTags?: any[]
  brandOwner?: string
  brandOwnerImported?: string
  brands?: string
  brandsTags?: string[]
  categories?: string
  categoriesHierarchy?: string[]
  categoriesImported?: string
  categoriesLc?: string
  categoriesOld?: string
  categoriesProperties?: CategoriesProperties
  categoriesPropertiesTags?: string[]
  categoriesTags?: string[]
  categoryProperties?: CategoriesProperties
  checkers?: any[]
  checkersTags?: any[]
  ciqualFoodNameTags?: string[]
  citiesTags?: any[]
  code?: string
  codesTags?: string[]
  comparedToCategory?: string
  complete?: number
  completeness?: number
  correctors?: string[]
  correctorsTags?: string[]
  countries?: string
  countriesHierarchy?: string[]
  countriesImported?: string
  countriesLc?: string
  countriesTags?: string[]
  createdT?: number
  creator?: string
  dataQualityBugsTags?: any[]
  dataQualityErrorsTags?: any[]
  dataQualityInfoTags?: string[]
  dataQualityTags?: string[]
  dataQualityWarningsTags?: string[]
  dataSources?: string
  dataSourcesImported?: string
  dataSourcesTags?: string[]
  debugParamSortedLangs?: string[]
  ecoscoreData?: EcoscoreData
  ecoscoreGrade?: string
  ecoscoreTags?: string[]
  embCodes?: string
  embCodes20141016?: string
  embCodesOrig?: string
  embCodesTags?: any[]
  entryDatesTags?: string[]
  expirationDate?: string
  foodGroups?: string
  foodGroupsTags?: string[]
  fruitsVegetablesNuts100GEstimate?: number
  genericName?: string
  genericNameEn?: string
  genericNameEs?: string
  genericNameFr?: string
  productID?: string
  imageFrontSmallURL?: string
  imageFrontThumbURL?: string
  imageFrontURL?: string
  imageIngredientsSmallURL?: string
  imageIngredientsThumbURL?: string
  imageIngredientsURL?: string
  imageNutritionSmallURL?: string
  imageNutritionThumbURL?: string
  imageNutritionURL?: string
  imageSmallURL?: string
  imageThumbURL?: string
  imageURL?: string
  images?: Images
  informers?: string[]
  informersTags?: string[]
  ingredients?: ProductIngredient[]
  ingredientsAnalysis?: any
  ingredientsAnalysisTags?: string[]
  ingredientsDebug?: Array<null | string>
  ingredientsFromOrThatMayBeFromPalmOilN?: number
  ingredientsFromPalmOilN?: number
  ingredientsFromPalmOilTags?: any[]
  ingredientsHierarchy?: string[]
  ingredientsIDSDebug?: string[]
  ingredientsLc?: string
  ingredientsN?: number
  ingredientsNTags?: string[]
  ingredientsOriginalTags?: string[]
  ingredientsPercentAnalysis?: number
  ingredientsTags?: string[]
  ingredientsText?: string
  ingredientsTextDebug?: string
  ingredientsTextEn?: string
  ingredientsTextFr?: string
  ingredientsTextEs?: string
  ingredientsTextEnImported?: string
  ingredientsTextWithAllergens?: string
  ingredientsTextWithAllergensEn?: string
  ingredientsTextWithAllergensEs?: string
  ingredientsTextWithAllergensFr?: string
  ingredientsThatMayBeFromPalmOilN?: number
  ingredientsThatMayBeFromPalmOilTags?: any[]
  ingredientsWithSpecifiedPercentN?: number
  ingredientsWithSpecifiedPercentSum?: number
  ingredientsWithUnspecifiedPercentN?: number
  ingredientsWithUnspecifiedPercentSum?: number
  ingredientsWithoutCiqualCodes?: string[]
  ingredientsWithoutCiqualCodesN?: number
  interfaceVersionCreated?: string
  interfaceVersionModified?: string
  knownIngredientsN?: number
  labels?: string
  labelsHierarchy?: string[]
  labelsLc?: string
  labelsOld?: string
  labelsTags?: string[]
  lang?: string
  languages?: Languages
  languagesCodes?: LanguagesCodes
  languagesHierarchy?: string[]
  languagesTags?: string[]
  lastEditDatesTags?: string[]
  lastEditor?: string
  lastImageDatesTags?: string[]
  lastImageT?: number
  lastModifiedBy?: string
  lastModifiedT?: number
  lastUpdatedT?: number
  lc?: string
  lcImported?: string
  link?: string
  mainCountriesTags?: any[]
  manufacturingPlaces?: string
  manufacturingPlacesTags?: any[]
  maxImgid?: string
  mineralsPrevTags?: any[]
  mineralsTags?: any[]
  miscTags?: string[]
  newAdditivesN?: number
  noNutritionData?: string
  novaGroup?: number
  novaGroupDebug?: string
  novaGroups?: string
  novaGroupsMarkers?: { [key: string]: Array<string[]> }
  novaGroupsTags?: string[]
  nucleotidesPrevTags?: any[]
  nucleotidesTags?: any[]
  nutrientLevels?: NutrientLevels
  nutrientLevelsTags?: string[]
  nutriments?: Nutriments
  nutriscore?: { [key: string]: Nutriscore }
  nutriscore2021_Tags?: string[]
  nutriscore2023_Tags?: string[]
  nutriscoreData?: NutriscoreData
  nutriscoreGrade?: string
  nutriscoreScore?: number
  nutriscoreScoreOpposite?: number
  nutriscoreTags?: string[]
  nutriscoreVersion?: string
  nutritionData?: string
  nutritionDataPer?: string
  nutritionDataPerImported?: string
  nutritionDataPrepared?: string
  nutritionDataPreparedPer?: string
  nutritionDataPreparedPerImported?: string
  nutritionGradeFr?: string
  nutritionGrades?: string
  nutritionGradesTags?: string[]
  nutritionScoreBeverage?: number
  nutritionScoreDebug?: string
  nutritionScoreWarningFruitsVegetablesLegumesEstimateFromIngredients?: number
  nutritionScoreWarningFruitsVegetablesLegumesEstimateFromIngredientsValue?: number
  nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredients?: number
  nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredientsValue?: number
  obsolete?: string
  obsoleteSinceDate?: string
  origin?: string
  originEn?: string
  origins?: string
  originsHierarchy?: string[]
  originsLc?: string
  originsOld?: string
  originsTags?: string[]
  otherNutritionalSubstancesTags?: any[]
  packaging?: string
  packagingHierarchy?: string[]
  packagingLc?: string
  packagingMaterialsTags?: any[]
  packagingOld?: string
  packagingOldBeforeTaxonomization?: string
  packagingRecyclingTags?: any[]
  packagingShapesTags?: string[]
  packagingTags?: string[]
  packagingText?: string
  packagingTextEn?: string
  packagingTextFr?: string
  packagingTextEs?: string
  packagings?: ProductPackaging[]
  packagingsComplete?: number
  packagingsMaterials?: PackagingsMaterials
  packagingsN?: number
  photographers?: string[]
  photographersTags?: string[]
  pnnsGroups1?: string
  pnnsGroups1_Tags?: string[]
  pnnsGroups2?: string
  pnnsGroups2_Tags?: string[]
  popularityKey?: number
  popularityTags?: string[]
  productName?: string
  productNameEn?: string
  productNameEs?: string
  productNameFr?: string
  productNameEnImported?: string
  productQuantity?: string
  productQuantityUnit?: string
  productType?: string
  purchasePlaces?: string
  purchasePlacesTags?: any[]
  quantity?: string
  removedCountriesTags?: any[]
  rev?: number
  scansN?: number
  selectedImages?: SelectedImages
  servingQuantity?: string
  servingQuantityUnit?: string
  servingSize?: string
  servingSizeImported?: string
  sortkey?: number
  sources?: Source[]
  sourcesFields?: SourcesFields
  states?: string
  statesHierarchy?: string[]
  statesTags?: string[]
  stores?: string
  storesTags?: any[]
  teams?: string
  teamsTags?: string[]
  traces?: string
  tracesFromIngredients?: string
  tracesFromUser?: string
  tracesHierarchy?: string[]
  tracesLc?: string
  tracesTags?: string[]
  uniqueScansN?: number
  unknownIngredientsN?: number
  unknownNutrientsTags?: any[]
  updateKey?: string
  vitaminsPrevTags?: any[]
  vitaminsTags?: any[]
  weighersTags?: any[]
}

export type IngredientsAnalysis = {
  enPalmOilContentUnknown?: string[]
  enVeganStatusUnknown?: string[]
  enVegetarianStatusUnknown?: string[]
}
